[tool.poetry]
name = "java-driver"
version = "3.7.1"
description = "ScyllaDB Java Driver"
authors = ["Java Driver Contributors"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3"
pygments = "2.2.0"
recommonmark = "0.6.0"
sphinx-scylladb-theme = "0.1.9"
sphinx-sitemap = "2.1.0"
sphinx-autobuild = "^0.7.1"
Sphinx = "2.4.4"
sphinx-multiversion = "0.2.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api" 
