name: "Doxygen"

on:
  push:
    branches:
    - master
    tags:       
    - '**'
jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Folder name
      id: folder_name
      run: echo ::set-output name=FOLDER_NAME::docs/_build/dirhtml/${GITHUB_REF#refs/*/}/api
    - name: Set up Doxygen
      run: sudo apt-get install doxygen
    - name: Build Doxygen docs
      run: |
        mkdir -p 
        echo "HTML_OUTPUT += ${GITHUB_REF#refs/*/}" >> Doxyfile
        doxygen doxyfile
    - name: Deploy
      run : ./docs/_utils/deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
