name: "CI Docs"

on:
  push:
    branches:
    - master
    tags:       
    - '**'
jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set up Doxygen
      run: sudo apt-get install doxygen
    - name: Build Sphinx docs
      run: |
        export PATH=$PATH:~/.local/bin
        cd docs
        make multiversion
    - name: Build Doxygen docs
      run: |
        echo 'Output dir: ${{ OUTPUT_DIR }}'
        mkdir -p ${{ OUTPUT_DIR }}
        echo 'HTML_OUTPUT = ${{ OUTPUT_DIR }}' >> Doxyfile
        doxygen doxyfile
      env:
        OUTPUT_DIR: 'docs/_build/dirhtml/${{ GITHUB_REF##*/ }}/api'
    - name: Deploy
      run : ./docs/_utils/deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
