name: "CI Docs"

on:
  push:
    branches:
    - master
    tags:       
    - '**'
jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set up Doxygen
      run: sudo apt-get install doxygen
    - name: Build Sphinx docs
      run: |
        export PATH=$PATH:~/.local/bin
        cd docs
        make multiversion
    - name: Configure Doxygen
      id: folder_name
      run: echo ::set-output name=FOLDER_NAME::docs/_build/dirhtml/${GITHUB_REF#refs/*/}/api
    - name: Build Doxygen docs
      run: |
        mkdir -p ${FOLDER_NAME}
        echo "HTML_OUTPUT += ${FOLDER_NAME}" >> Doxyfile
        doxygen doxyfile
    - name: Deploy
      run : ./docs/_utils/deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
